<?php

return [
    "github.com" => [
        "format" => "^https?://(www\.)?github\.com/(?<username>[a-zA-Z0-9._-]+)/(?<repository>[a-zA-Z0-9._-]+)/?$",
        "badges" => [
            [
                "title" => "latest release",
                "badge" => "https://badgen.net/github/release/[username]/[repository]",
                "link" => "", "text" => "latest release",
            ],
            [
                "title" => "latest stable release",
                "badge" => "https://badgen.net/github/release/[username]/[repository]/stable",
                "link" => "",
                "text" => "latest stable release",
            ],
            [
                "title" => "latest tag",
                "badge" => "https://badgen.net/github/tag/[username]/[repository]",
                "link" => "",
                "text" => "latest tag",
            ],
            [
                "title" => "watchers",
                "badge" => "https://badgen.net/github/watchers/[username]/[repository]",
                "link" => "",
                "text" => "watchers",
            ],
            [
                "title" => "combined checks (default branch)",
                "badge" => "https://badgen.net/github/checks/[username]/[repository]",
                "link" => "",
                "text" => "combined checks (default branch)",
            ],
            [
                "title" => "combined statuses (default branch)",
                "badge" => "https://badgen.net/github/status/[username]/[repository]",
                "link" => "",
                "text" => "combined statuses (default branch)",
            ],
            [
                "title" => "combined statuses (branch)",
                "badge" => "https://badgen.net/github/status/[username]/[repository]/gh-pages",
                "link" => "",
                "text" => "combined statuses (branch)",
            ],
            [
                "title" => "combined statuses (commit)",
                "badge" => "https://badgen.net/github/status/[username]/[repository]/f4809eb6df80b",
                "link" => "",
                "text" => "combined statuses (commit)",
            ],
            [
                "title" => "combined statuses (tag)",
                "badge" => "https://badgen.net/github/status/[username]/[repository]/4.0.1",
                "link" => "",
                "text" => "combined statuses (tag)",
            ],
            [
                "title" => "single status",
                "badge" => "https://badgen.net/github/status/[username]/[repository]/master/ci/circleci:%20lint",
                "link" => "",
                "text" => "single status",
            ],
            [
                "title" => "combined statuses (ci*)",
                "badge" => "https://badgen.net/github/status/[username]/[repository]/master/ci",
                "link" => "",
                "text" => "combined statuses (ci*)",
            ],
            [
                "title" => "combined statuses (ci/circleci*)",
                "badge" => "https://badgen.net/github/status/[username]/[repository]/master/ci/circleci",
                "link" => "",
                "text" => "combined statuses (ci/circleci*)",
            ],
            [
                "title" => "single status",
                "badge" => "https://badgen.net/github/status/[username]/[repository]/master/ci/circleci:%20build",
                "link" => "",
                "text" => "single status",
            ],
            [
                "title" => "stars",
                "badge" => "https://badgen.net/github/stars/[username]/[repository]",
                "link" => "",
                "text" => "stars",
            ],
            [
                "title" => "forks",
                "badge" => "https://badgen.net/github/forks/[username]/[repository]",
                "link" => "",
                "text" => "forks",
            ],
            [
                "title" => "issues",
                "badge" => "https://badgen.net/github/issues/[username]/[repository]",
                "link" => "",
                "text" => "issues",
            ],
            [
                "title" => "open issues",
                "badge" => "https://badgen.net/github/open-issues/[username]/[repository]",
                "link" => "",
                "text" => "open issues",
            ],
            [
                "title" => "closed issues",
                "badge" => "https://badgen.net/github/closed-issues/[username]/[repository]",
                "link" => "",
                "text" => "closed issues",
            ],
            [
                "title" => "issues by label",
                "badge" => "https://badgen.net/github/label-issues/[username]/[repository]/ES%20Modules",
                "link" => "",
                "text" => "issues by label",
            ],
            [
                "title" => "open issues by label",
                "badge" => "https://badgen.net/github/label-issues/[username]/[repository]/help-wanted/open",
                "link" => "",
                "text" => "open issues by label",
            ],
            [
                "title" => "closed issues by label",
                "badge" => "https://badgen.net/github/label-issues/[username]/[repository]/B-RFC-approved/closed",
                "link" => "",
                "text" => "closed issues by label",
            ],
            [
                "title" => "PRs",
                "badge" => "https://badgen.net/github/prs/[username]/[repository]",
                "link" => "",
                "text" => "PRs",
            ],
            [
                "title" => "open PRs",
                "badge" => "https://badgen.net/github/open-prs/[username]/[repository]",
                "link" => "",
                "text" => "open PRs",
            ],
            [
                "title" => "closed PRs",
                "badge" => "https://badgen.net/github/closed-prs/[username]/[repository]",
                "link" => "",
                "text" => "closed PRs",
            ],
            [
                "title" => "merged PRs",
                "badge" => "https://badgen.net/github/merged-prs/[username]/[repository]",
                "link" => "",
                "text" => "merged PRs",
            ],
            [
                "title" => "milestone percentage",
                "badge" => "https://badgen.net/github/milestones/[username]/[repository]/1",
                "link" => "",
                "text" => "milestone percentage",
            ],
            [
                "title" => "commits count",
                "badge" => "https://badgen.net/github/commits/[username]/[repository]",
                "link" => "",
                "text" => "commits count",
            ],
            [
                "title" => "commits count (branch ref)",
                "badge" => "https://badgen.net/github/commits/[username]/[repository]/gh-pages",
                "link" => "",
                "text" => "commits count (branch ref)",
            ],
            [
                "title" => "commits count (tag ref)",
                "badge" => "https://badgen.net/github/commits/[username]/[repository]/4.0.1",
                "link" => "",
                "text" => "commits count (tag ref)",
            ],
            [
                "title" => "last commit",
                "badge" => "https://badgen.net/github/last-commit/[username]/[repository]",
                "link" => "",
                "text" => "last commit",
            ],
            [
                "title" => "last commit (branch ref)",
                "badge" => "https://badgen.net/github/last-commit/[username]/[repository]/gh-pages",
                "link" => "",
                "text" => "last commit (branch ref)",
            ],
            [
                "title" => "last commit (tag ref)",
                "badge" => "https://badgen.net/github/last-commit/[username]/[repository]/4.0.1",
                "link" => "",
                "text" => "last commit (tag ref)",
            ],
            [
                "title" => "branches",
                "badge" => "https://badgen.net/github/branches/[username]/[repository]",
                "link" => "",
                "text" => "branches",
            ],
            [
                "title" => "releases",
                "badge" => "https://badgen.net/github/releases/[username]/[repository]",
                "link" => "",
                "text" => "releases",
            ],
            [
                "title" => "tags",
                "badge" => "https://badgen.net/github/tags/[username]/[repository]",
                "link" => "",
                "text" => "tags",
            ],
            [
                "title" => "license",
                "badge" => "https://badgen.net/github/license/[username]/[repository]",
                "link" => "",
                "text" => "license",
            ],
            [
                "title" => "contributors",
                "badge" => "https://badgen.net/github/contributors/[username]/[repository]",
                "link" => "",
                "text" => "contributors",
            ],
            [
                "title" => "assets downloads for latest release",
                "badge" => "https://badgen.net/github/assets-dl/[username]/[repository]",
                "link" => "",
                "text" => "assets downloads for latest release",
            ],
            [
                "title" => "assets downloads for a tag",
                "badge" => "https://badgen.net/github/assets-dl/[username]/[repository]/v7.0.0",
                "link" => "",
                "text" => "assets downloads for a tag",
            ],
            [
                "title" => "repository dependents",
                "badge" => "https://badgen.net/github/dependents-repo/[username]/[repository]",
                "link" => "",
                "text" => "repository dependents",
            ],
            [
                "title" => "package dependents",
                "badge" => "https://badgen.net/github/dependents-pkg/[username]/[repository]",
                "link" => "",
                "text" => "package dependents",
            ],
        ],
    ],
];
